### PR TITLE
Not actually  PR - Just a question!

### PR DESCRIPTION
**Pull request by bbbbbr**
This isn't actually a PR, just using PRs since issues aren't enabled for this repo and I wanted to ask question:

Looks like you've done a bunch of work on improving the compression and fixing a couple other things. Are you open to me merging some of your fixes into my fork? (with credit noted if so) No worries if not :+1: 

(https://github.com/bbbbbr/gb-wordle) 

(The reverse is also welcome of course! my changes have moved a lot of code)

### CODE REVIEW

**Comment by arpruss** [comment]
I think it might take more time than I have to make the things fit together.

**Comment by bbbbbr** [comment]
Sorry if I wasn't clear - I just wanted to know whether it would be ok for me to use your fixes in my fork. I would handle all the merging. Again, no worries if not.

Thanks!

**Comment by arpruss** [comment]
Yeah, sure. It's all GPL3 code.

**Comment by bbbbbr** [comment]
Thanks!

**Comment by bbbbbr** [comment]
Since you re-opened this PR: in case you're interested here's a link to a review of the compression output and code size. I didn't measure speed yet (might still).
https://github.com/bbbbbr/gb-wordle/blob/compress_arpruss/wordle_compress/compress_comparison.md

**Comment by arpruss** [comment]
1. Nice comparison. I am surprised my code is so big, though you should take into account that the zeta_two code pulls in 32-bit multiply, divide and modulus library code, which is about 600 bytes total. It's still the winner size-wise. :-)
2. There is also speed to be considered. That's mostly the speed of generating a new word or of searching for one. Some of the size difference is due to the fact that I have some things unrolled while zeta_two has a loop. For most of that, a loop is fine, but decodeInt() is probably best unrolled for speed.
3. I optimized a bunch of the decode code for size just now. :-)
4. BTW, experiment suggests that you can save some compression size by reversing the encoding of the words right-to-left in the zeta_two algorithm.

**Comment by bbbbbr** [comment]
Good points!

Maybe I'll merge in your optimizations and also do some benchmarking soon. Should be interesting

The top summary data should factor in any system libs since measuring the ROM file (it's harder to measure size for system libs since those don't show up in the .cdb). This is using https://github.com/bbbbbr/romusage

I haven't been building with additional optimizations on (`-Wf--max-allocs-per-node50000` or even `-Wf--max-allocs-per-node250000`) which appears to squeeze another 200-300 bytes out of total ROM size and may improve performance. But those are add noticeable of compile time (34 vs 3 seconds for clean build)  on my old computer.

**Comment by arpruss** [comment]
I get the size of the libs from the .map file.

**Comment by bbbbbr** [comment]
Did some profiling and updated the comparison
https://github.com/bbbbbr/gb-wordle/blob/compress_arpruss/wordle_compress/compress_comparison.md

**Comment by arpruss** [comment]
Based on the profiling, I would recommend you go with mine because of the speed of verification. My feeling is that 0.25 seconds to verify a word is a noticeable bit of a latency. (To be honest, in practice I can even notice the shorter verification delay when I play my version.)

BTW, I added some auto-repeat joypad code, but I am not completely happy with it.

**Comment by arpruss** [comment]
And I did more optimization. :-)

**Comment by bbbbbr** [comment]
Agreed, faster AND smaller is hard to beat. :)  Especially since the 0.25 seconds on CGB becomes 0.5 seconds on original Game Boy, definitely noticeable.

I have a simple & non-blocking key repeat I pulled in from Petris which I haven't turned on yet. Looks something like: 

```
#define UPDATE_KEY_REPEAT(MASK) if (MASK & previous_keys & keys) { key_repeat_count++; } else { key_repeat_count=0; }
#define RESET_KEY_REPEAT(NEWVAL) key_repeat_count = NEWVAL
...
 UPDATE_KEY_REPEAT((J_LEFT | J_RIGHT | J_DOWN));
...
    if (KEY_PRESSED(J_LEFT)) {
        if (key_repeat_count == KEY_REPEAT_START)
            // Do something
        else if (key_repeat_count >= KEY_REPEAT_LEFTRIGHT_THRESHOLD) {
            // Do it again after a small delay, and repeat thereafter using a shorter delay
            RESET_KEY_REPEAT(KEY_REPEAT_LEFTRIGHT_RELOAD);
        }
    }
```

**Comment by arpruss** [comment]
BTW, the best word for testing filter speed is SZZZZ, since S is the most common starting letter.
I think key repeat is working fine for me just by changing waitpadup() to waitpaduprepeat():
`static void waitpaduprepeat() {
    static uint16_t delta = (uint32_t)350 * CLOCKS_PER_SEC / 1000;
    uint8_t j;
    uint16_t start = sys_time;
    while ((j = joypad()) && (uint16_t)(sys_time-start) < delta) ;
    if (j)
        delta = (uint32_t)100 * CLOCKS_PER_SEC / 1000;
    else
        delta = (uint32_t)350 * CLOCKS_PER_SEC / 1000;
}
`

**Comment by bbbbbr** [comment]
Just pasting this here since I'm finishing up for the night, but can make a separate PR later if you're want. 

Finally got around to fixing the random word selection (looks like you already did that) by lifting the 211 cap and using randw() for a 16 bit return. That prompted a little optimizing on `getSpecialWord()`. The biggest gains come from using static locals instead of stack vars, and then a little more from making `n` unsigned with nonzero test and using the bitmask as the loop counter.

For retrieving word `2200`
From: 1601086 cycles  (22.80 frames, 0.38 seconds)
To: 942024 cycles (13.41 frames, 0.22 seconds)

```
void getSpecialWord(uint16_t n, char* buffer) {

    static uint8_t i;
    static uint8_t bit_data;
    static uint16_t w;
    static const uint8_t* b;

    n++; // Indexing offset
    b = answers;
    w = 0u;

    while(n != 0u) {
        bit_data = *b;
        if (bit_data == 0u) {
            w += 8u;
        }
        else {
            // After final upshift i becomes 0x00 and loop exits
            for (i = 0x01u ; i != 0x00u; i <<= 1) {
                if (bit_data & i) {
                    n--;
                    if (n == 0u)
                        break;
                }
                w++;
            }
        }
        b++;
    }
    getWord(w, buffer);
}
```

**Comment by arpruss** [comment]
Good ideas! I forgot that static is often faster than stack on old systems.

I just did a bunch more optimizations to decode.c. I don't have an easy way to measure speed, but I am thinking that size is a proxy for speed.

**Comment by arpruss** [comment]
Wow! I assumed that rand() was 16-bit, but it's only 8-bit. I fixed this. I also did things slightly more efficiently by dropping the high bits so we don't loop as many times in getting the random word.

**Comment by bbbbbr** [comment]
The profiler I've been using is part of Emulicious:
https://emulicious.net/

The other option (works in BGB and Emulicious) is emu_debug.h:
`EMU_PROFILE_BEGIN` and `EMU_PROFILE_END` 
https://gbdk-2020.github.io/gbdk-2020/docs/api/emu__debug_8h.html
There's an `emu_debug` project in the examples folder

**Comment by bbbbbr** [comment]
Seemed like `getSpecialWord()` was getting closer to the limits of SDCC's C optimization so I made a first pass in asm. There is probably more room to optimize since my asm is so-so, but it's a decent speedup.

For the most recent version it's reduced from 762528 CGB cycles to 260998 CGB cycles (not counting the 119660 cycles from it's call to `getWord`). 

https://github.com/bbbbbr/gb-wordle/commit/8053ae67062d6578e634d30eadc687e14c1e7677

**Comment by arpruss** [comment]
1. You should probably integrate my recent optimizations for some of the other functions--e.g., the switch to globals for variable-length integer decoding.
2. I moved the word generation code to AFTER displaying the first letter entered by the user. This prevents an annoying slight delay for the first button press of a game, especially since that delay could be used to provide the user with a hint as to what word it is (i.e., if the delay feels long, the word is likely to start with a more common first letter and be further down in the alphabet). 
3. An algorithmic generateSpecialWord() optimization that could be done, and which could in theory provide a speedup, would be to use an addition table. The cost is 256 bytes of RAM. Would you be able to benchmark my attempt?  https://gist.github.com/arpruss/977a0e30f73a8f58732bc41a0da5264a

**Comment by arpruss** [comment]
It's been about two decades since I've done Z80 assembly. I redid updateWord() in assembly. I haven't benchmarked, but I expect it's quite a bit faster.

**Comment by bbbbbr** [comment]
1. I think I already merged in your recent updates, but will look over them again
2. Yes, that's a good idea. Eventually I'll add a title screen and was going to attach the rand init to it's exit, but after first letter entry does seem like the most unobtrusive place.
3. Sure I can benchmark soon. Nice approach.

I was thinking about another `getSpecialWord()` speedup: pre-calculate a small set of offsets into the bitmapped index, say once every ~128 or ~256 answer words (using word nums which align to index whole bytes), which would allow it to fast forward through a lot of the computation. If the distance is small enough (haven't checked) then per entry it could just store two bytes: one for answer letter num deltas, one for bitmap index deltas.

Then as a step before the main loop (just rough, haven't tested):
```
    const uint8_t * b_index = answers_index;
    while (n >= *b_index) {
        n -= *b_index++;
        w += *b_index * 8u;
        b += *b_index++;
    }
```

Might also be possible to calculate `w` from something like final pointer difference vs index, and then adding the bits from the final byte instead of incrementing it every single bit.

**Comment by bbbbbr** [comment]
### updateWord()
For your asm version of updateWord (looking up word 2200) there is a significant speedup:
```
C version:
	_getWord		120228
		_updateWord		103818

ASM version:
	_getWord		53552
		_updateWord		37142
```

### getSpecialWord()
All cycle counts are self time, CGB mode, excluding getWord()

Your version with the lookup table got a significant speed boost too:
```
Previous: 762528
With LUT: 429396
```

I optimized my asm version to calculate the word index from the pointer. Did not yet try to adding in your lookup table or the other speedup idea.
```
Previous: 260998
Current :  179330
```
https://github.com/bbbbbr/gb-wordle/blob/ded38221ed4b1745e3181175ba4f477f25d53520/src/decode.c

**Comment by arpruss** [comment]
I now think the best way to make getSpecialWord() be fast is to have buckets. So there are now 10 buckets. The cost is 116 bytes for the data and code. If we want any more speed up, we can just increase the number of buckets, at a cost of 4 bytes per bucket. This seems easier than maintaining assembly code for getSpecialWord().

**Comment by bbbbbr** [comment]
Starting to reach the point of diminishing returns. :) It's impressive versus the previous 1601086 cycles.

Your current version with 10 buckets:
`_getSpecialWord		100516 (39,664 self time)`

I updated the ASM version and converted the bucket struct to 8 bits and changed the offsets to deltas. Then increased buckets to 15. It's about 100 bytes smaller.
`_getSpecialWord		58502	(4950 self time)`

For now it's plenty of speedup so I'm going to switch back to improving features.

**Comment by bbbbbr** [comment]
An update. I wanted to free up some more space, so tried a couple of strategies I'd seen discussed for improving the compression. In the end there was about a 4.5K gain including decompression code-size (in C, so some size and speed gains likely remain there).

I settled on the combo below and using compression (already in the code base) for the answer bitmap. Since word data is now nybble packed, an improved dictionary index (more than first-letter only) was needed to keep lookup speed fast. 
`5-bit  3-bit  w-rev  freq-2 :  13,812`


```
Per-letter numeric encoding
 * 5-bit: 5 bits / letter
 * b-26:  Base 26 letters

Calculated word-to-word numeric delta encoding
* 7-bit: 7 bit variable encoding (byte size decoding)
* 4-bit: Escaped 4 bit variable encoding (first nybble 3-bit, flag bit indicates value or num of following 4-bit nybbles)
* 3-bit: 3 bit variable encoding (nybble size decoding)

Word letter order
 * Norm: Normal letter order (bakes -> bakes)
 * Rev:  Reversed letter order (bakes -> sekab)

Alphabet Reordering
 * Norm: Normal alphabet order (abcde..xyz)
 * Freq-1: Reorder alphabet using ~frequency of use
 * Freq-2: Reorder alphabet using a recommended order

Uncompressed size:
12,965 × 5 = 64,825

Letter Wordval W-Ord Alpha
5-bit  7-bit                :  17,757
5-bit  7-bit  W-Rev  Freq-2 :  16,562
B-26   7-bit  W-Rev  Freq-2 :  16,248

5-bit  4-bit  W-Rev  Freq-2 :  15,368

5-bit  3-bit                :  16,315
5-bit  3-bit         Freq-2 :  15,359
5-bit  3-bit  W-Rev         :  14,869
5-bit  3-bit  w-rev  freq-2 :  13,812

B-26   3-bit                :  15,631
B-26   3-bit  W-Rev         :  14,304
B-26   3-bit  W-Rev  Freq-1 :  13,632
B-26   3-bit  W-Rev  Freq-2 :  13,253
```

**Pull request closed without merging**
